# A decaying history of error channels
Recall that unital channels are a convex set. Consider the convex combination of the dephasing channels that would have generated the last $N$ errors. Let $M_t$ be the $t^{\text{th}}$ Bloch matrix, then our approximation of the channel is

$$ \hat{M} = \sum_t e^{- \lambda t} M_t $$

We will exploit the structure of the plateaus: say we see no errors for $n$ steps then an $X$ error. We will assume this was generated by the channel

$$ M_t = \left[ \begin{array}{ccc} 1 & 0 & 0 \\ 0 & 1-1/n_t & 0 \\ 0 & 0 & 1-1/n_t \end{array} \right] $$

Really, $M_t$ can be any window of time so long as we get a good estimate of $a_x$, $a_y$, and $a_z$.

We add this channel to our decaying sequence to find our $\hat{M}$. Then we diagonalize $\hat{M}$ to find $\hat{Q}$ and apply $\hat{Q}$ such that we order our axes as $Y$, $Z$, $X$ from lowest to highest rate.

We get $\hat{Q}$ by minimizing

$$ \left\| \hat{Q} \hat{M} \hat{Q}^T - S\right\| $$

where

$$ S = \left[ \begin{array}{ccc} 1- \kappa p & 0 & 0 \\ 0 & 1-p-\kappa p & 0 \\ 0 & 0 & 1-p \end{array} \right] $$

Could it be that Q is upper diag? Could we solve the minimum to the Sylvester equation by using Q = exp(G)?

The norm we are looking for is quite specific. We are only interested in the difference of diagonal elements. So this is technically the... $1$-norm?

$$ \mathrm{Tr} \left[ \left| \hat{Q}\hat{S}\hat{Q}^T - V \right| \right] $$

In [410]:
import numpy as np

def RotInto(source, target):
    a = source / np.linalg.norm(source)
    b = target / np.linalg.norm(target)

    v = np.cross(a, b)
    c = np.dot(a, b)
    s = np.linalg.norm(v)
    u = v / np.linalg.norm(v)
    
    V = np.array([
            [0, -u[2], u[1]],
            [u[2], 0, -u[0]],
            [-u[1], u[0], 0]
        ])
    
    R = c * np.eye(3) + s * V + (1-c) * np.outer(u, u)
    return R

In [416]:
source = np.random.random(3)*10.0
target = np.random.random(3)*10.0
R = RotInto(source, target)

1.73205080757
[[  1.00000000e+00   1.38777878e-17  -1.73472348e-17]
 [  1.38777878e-17   1.00000000e+00   5.55111512e-17]
 [ -1.73472348e-17   5.55111512e-17   1.00000000e+00]]
[  5.55111512e-17   0.00000000e+00   0.00000000e+00]
