In [8]:
% load_ext autoreload
% autoreload 2
% matplotlib inline

from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
import scipy as sp
import seaborn as sns
np.set_printoptions(precision=4, linewidth=120)
from tqdm import *
from drift_qec.Q import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [9]:
D = 0.25*np.pi
channel = Channel(kx=0.7, ky=0.2, kz=0.1, Q=FIXEDQ,
                  n=1e2, d1=D, d2=D, d3=D)
for _ in range(1000):
    channel.update()
print channel.C
print channel.Mhat

[[ 0.1317  0.1109 -0.0285]
 [ 0.1109  0.5553 -0.2122]
 [-0.0285 -0.2122  0.3128]]
[[ 0.1314  0.1097 -0.0334]
 [ 0.1097  0.5537 -0.2127]
 [-0.0334 -0.2127  0.3149]]


In [10]:
D = 0.25 * np.pi
channel = Channel(kx=0.7, ky=0.2, kz=0.1, Q=FIXEDQ,
                  n=1e5, d1=D, d2=D, d3=D)
channel.update()
print channel.C
print channel.Mhat

[[ 0.1317  0.1109 -0.0285]
 [ 0.1109  0.5553 -0.2122]
 [-0.0285 -0.2122  0.3128]]
[[ 0.1297  0.1127 -0.0276]
 [ 0.1127  0.5579 -0.2126]
 [-0.0276 -0.2126  0.3124]]
